server:
  servlet:
    context-path: /celestial-body
  port: 5001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1000/GA_CELESTIAL_BODY
    username: admin
    password: admin

  liquibase:
    enabled: true
    change-log: classpath:database/master-changelog.xml

  jpa:
    show-sql: true